# -*- coding: utf-8 -*-
"""PandasyCSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHRdL_f_U8gjs3eYbsRrUZP1V4cVG5pv

### 1. Carga de datos: Llamando u narchivo CSV utilizando pandas
"""

import pandas as pd
#from google.colab import files
#uploaded =files.upload()
#Esto permite subir un archivo del pc
df = pd.read_csv("/content/CSV/mv.csv")
#De otra manera puede agregarse código desde dirve a la carpeta raíz.
print(df.head())
df.info()

"""### 2. Exploración básica: Muestra las primeras 5 filas, las últimas 5 filas, y un resúmen estadístico de los datos

Bien, aquí simplemente estamos invedagando un poco sobre los que se puede hacer con jupiter, es conveniente buscar el proceso especifico para la tarea por realizar.
"""

# Ver las primeras 5 filas
print(df.head())
# Ver las últimas 5 filas
print(df.tail())

"""### 3. Información del DataFrame: Muestra la información del Data-Frame (tipos de datosm columnas, etc)."""

# Ver información técnica (tipos de datos, valores nulos)
df.info()

# Ver estadísticas básicas de columnas numéricas
df.describe()



# Ver los nombres de las columnas
print(df.columns)

"""### Parte 2: Limpieza de Datos

#### Comencemos con la limpieza de los datos.
1. Muestra la cantidad de valores nulos y eliimnar valores faltantes.
2. Rellenar valores falantes con 0
3. Eliminar columnas innecesarias

#### ¿Qué es un valor nulo/faltante?
- Es un espacio vacío en tu dataser que no tiene información.
- En pandas se representa como: NaN (not a nuber) o none.
- Puede ocurrir por: errores de captura, datos no disponibles, campos opcionales
- Pueden afectar cálculos y análisis.

1. Muestra la cantidad de valores nulos y eliminar valores faltantes
"""

# Ver si hay nulos en cada columna (TRUE FALSE)
print(df.isnull())

# Contar nulos en cada columna.
df.isnull().sum()

#Contar TOTSL de nulos por DataFrame
total_nulos = df.isnull().sum().sum()
print(total_nulos)

# Ver porcentaje de nulos por la columna (Para evaluar gravedad)
porcentaje_nulos = df.isnull().mean() * 100
print(porcentaje_nulos)

# Información completa incluyendo nilos
df.info()

"""## Hasta ahora no hay señal de nigún valor nulo."""

# Pudieron haberse eliminado..
df_limpio = df.dropna()
# Elimina filas con al menos 1 nulo
df_limpio = df.dropna(axis=0) #Lo mismo (axis=0 filas)
print(df_limpio)

"""### Ahora, rellanamos valores faltantes

### ¿Por qué rellenar con 0?
- Útil cuando el valor faltante repesenta "ausencia de cantidad"
- Ejemplo: ventas = 0 (no hubo venta), no es lo mismo que dato desconocido
- No se pierden filas del dataset
- No usar si cero significa "dato desconocido"

2. Rellenar valores faltantes: Rellena los valores faltantes con 0.
"""

df.fillna(0)

#Rellenar solo columnas específicas con cero
df['Unnamed: 0'] = df['Unnamed: 0'].fillna(0)
print(df)

#Esto reemplaza TODOS los Nan en TODO el dataframe con 0
df_relleno_0 = df.fillna(0)
print(df_relleno_0)

#Rellenar múltiples columnas específicas
columnas_a_rellenar = ['Unnamed: 0', 'time', 'carrera']
df[columnas_a_rellenar] = df[columnas_a_rellenar].fillna(0)
print(df)

"""### Al menos en esé dataset no hay que rellenar ningún NaN

3.  Eliminar coñumnas innecesarias: Elimina una columna que no sea relevante para el análisis.
"""

#df.dropna() Elimina filas inneecesarias

"""### Parte 3: Filtrado y Selección de Datos

### Filtrar filas con múltiples condiciones en pandas

#### ¿Qué es filtrar con múltiples condiciones?
- Seleccionar filas que cumplan 2 o más criterios simultáneamente
- Se usan operadores lógicos: & (Y), | (O), ~ (No)
- Cada condición debe de ir en parétesis
- & AND , | OR,
~ Not

1. FIltrar con múltiples condiciones: Filtra las filas que cúmplen con múltiples condiciones.
"""

db_filtrado = df[df["edad"] >= 18]
db_filtrado

"""- Más de un rango de edad"""

db_filtrado = df[(df["edad"] >= 18) & (df["edad"] <50)]
db_filtrado

"""#### Parte 4: Operaciones y Agrupación

1. Calcula la suma, media de la columna
"""

df = df['edad'].sum()
df

"""#### Hacer esto cambio el contenido y evito que el resto del código funcionará correctamente"""

media = df_filtrado['edad'].mean()
media

"""2. Agrupa los datos por la columna y calcula la media de otra columna para cada grupo."""

df.groupby('sexo')['edad'].mean()

"""3. Crear una tabla pivote para resumir los datos"""

df.pivot_table(
    values="edad",
    index="time",
    columns=["carrera", "acepta", "trabajo"],
    aggfunc = "mean"
)

"""#### Parte 5: Manipulación de Datos.

Ordenar datos: Ordena el DataFrame por una columna especifica.
"""

df.sort_values("carrera")

"""#### Ejercicio 6: Guardar Resultados

Guardar DataFrame: Guarda el DataFrame modificado en un nuevo archivo CSV.
"""

df.to_csv("DataFrameMod.csv", index=False)